# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://0x6368616e67.com/"
#baseURL = "http://127.0.0.1/"
title = "0x6368616e67"
enableRobotsTXT = true
enableEmoji = true
theme = "cz-jane"


hasCJKLanguage = true     
paginate = 5              
copyright = "0x6368616e67"    

[RSS]
  limit=10

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           
[languages.en]
  languageCode = "en"

[author]                  
  name = "0x6368616e67"

[sitemap]                 
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Categories"
  weight = 20
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Archives"
  weight = 30
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"


[params]
  since = "2018"            
  homeFullContent = false   


  # site info (optional) 
  logoTitle = "0x6368616e67"        
  logoImage = "/images/logo.png"
  keywords = ["0x6368616e67", "rust","blockchain"]
  description = "0x6368616e67"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  toc = true   # 是否开启目录
  photoswipe = true         
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'


  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social] 
    a-email = "mailto:0x6368616e67@gmail.com"
    g-github = "https://github.com/0x6368616e67/"

  [params.utteranc]    
    enable = true
    repo = "0x6368616e67/0x6368616e67.com"
    issueTerm = "pathname"
    theme = "github-light"
